小进展

diff --git a/uCore/sourcecode/Makefile b/uCore/sourcecode/Makefile
--- a/uCore/sourcecode/Makefile
+++ b/uCore/sourcecode/Makefile
@@ -4,25 +4,12 @@ SPACE	:= $(EMPTY) $(EMPTY)
 SLASH	:= /
 
 V       := @
-#need llvm/cang-3.5+
-#USELLVM := 1
-# try to infer the correct GCCPREFX
-ifndef GCCPREFIX
-GCCPREFIX := $(shell if i386-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
-	then echo 'i386-elf-'; \
-	elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
-	then echo ''; \
-	else echo "***" 1>&2; \
-	echo "*** Error: Couldn't find an i386-elf version of GCC/binutils." 1>&2; \
-	echo "*** Is the directory with i386-elf-gcc in your PATH?" 1>&2; \
-	echo "*** If your i386-elf toolchain is installed with a command" 1>&2; \
-	echo "*** prefix other than 'i386-elf-', set your GCCPREFIX" 1>&2; \
-	echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
-	echo "*** To turn off this error, run 'gmake GCCPREFIX= ...'." 1>&2; \
-	echo "***" 1>&2; exit 1; fi)
-endif
 
-# try to infer the correct QEMU
+# 尝试去指向当前环境下的QEMU
+# 这里用到了Shell if-fi 中间分支使用elif else分隔
+# /dev/null相当于黑洞，其本质就是不希望which的输出显示，但是whitch的值依然会被if捕获
+# 对if条件一个详细的解释在https://blog.csdn.net/timo1160139211/article/details/74079553
+# 简而言之就是if判断的是表达式执行的退出状态码，为0代表成功，非0代表失败，而不是说直接传入的数值也能被使用
 ifndef QEMU
 QEMU := $(shell if which qemu-system-i386 > /dev/null; \
 	then echo 'qemu-system-i386'; exit; \
@@ -37,16 +24,39 @@ QEMU := $(shell if which qemu-system-i386 > /dev/null; \
 	echo "***" 1>&2; exit 1; fi)
 endif
 
-# eliminate default suffix rules
+#need llvm/cang-3.5+
+#USELLVM := 1
+# try to infer the correct GCCPREFX
+# 管道是stdin->stdout,是两个进程，而重定向是在一个进程中完成的
+# 2>&1表达的是将标准错误重定向到标准输出
+# objdump -i 中的-i是Info的意思 查看-b 或者 -m选项可用的架构
+# 总之1>&2或者2>&1完成将echo 的输出在标准输入和标准输出中切换
+# 最终结果根据当前环境来返回GCC对应的二前缀，或是“i386-elf-”或是“”再或者是错误提示信息
+ifndef GCCPREFIX
+GCCPREFIX := $(shell if i386-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
+	then echo 'i386-elf-'; \
+	elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
+	then echo ''; \
+	else echo "***" 1>&2; \
+	echo "*** Error: Couldn't find an i386-elf version of GCC/binutils." 1>&2; \
+	echo "*** Is the directory with i386-elf-gcc in your PATH?" 1>&2; \
+	echo "*** If your i386-elf toolch ain is installed with a command" 1>&2; \
+	echo "*** prefix other than 'i386-elf-', set your GCCPREFIX" 1>&2; \
+	echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
+	echo "*** To turn off this error, run 'gmake GCCPREFIX= ...'." 1>&2; \
+	echo "***" 1>&2; exit 1; fi)
+endif
+
+# eliminate 默认后缀会泽
 .SUFFIXES: .c .S .h
 
 # delete target files if there is an error (or make is interrupted)
 .DELETE_ON_ERROR:
 
-# define compiler and flags
+# 定义编译器以及标志
 ifndef  USELLVM
 HOSTCC		:= gcc
-HOSTCFLAGS	:= -g -Wall -O2
+HOSTCFLAGS	:= -g -Wall -O2 #-Wall 不忽略任何警告 -O2采用O2优化级别, 一共有四个级别O0 O1 O2 O3 -g指示编译器在编译的时候产生调试信息
 CC		:= $(GCCPREFIX)gcc
 CFLAGS	:= -fno-builtin -Wall -ggdb -m32 -gstabs -nostdinc $(DEFS)
 CFLAGS	+= $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
@@ -58,25 +68,27 @@ CFLAGS	:= -fno-builtin -Wall -g -m32 -mno-sse -nostdinc $(DEFS)
 CFLAGS	+= $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
 endif
 
+# 定义C文件类型
 CTYPE	:= c S
 
 LD      := $(GCCPREFIX)ld
 LDFLAGS	:= -m $(shell $(LD) -V | grep elf_i386 2>/dev/null)
 LDFLAGS	+= -nostdlib
 
+# 常用命令定义
 OBJCOPY := $(GCCPREFIX)objcopy
 OBJDUMP := $(GCCPREFIX)objdump
 
 COPY	:= cp
-MKDIR   := mkdir -p
+MKDIR   := mkdir -p # -p参数确保创建子文件夹的时候父文件夹中存在
 MV		:= mv
-RM		:= rm -f
-AWK		:= awk
-SED		:= sed
-SH		:= sh
-TR		:= tr
-TOUCH	:= touch -c
-
+RM		:= rm -f 
+AWK		:= awk #对文本和数据进行处理，相关资料 https://www.cnblogs.com/quincyhu/p/5884390.html
+SED		:= sed #sed是非交互式的编辑器。相关资料 http://www.cnblogs.com/edwardlost/archive/2010/09/17/1829145.html
+SH		:= sh #shell命令语言解释器
+TR		:= tr #tr命令可以对来自标准输入的字符进行替换、压缩和删除 http://man.linuxde.net/tr
+TOUCH	:= touch -c #加入-c参数不建立任何文件，只是更新时间戳
+# 目录
 OBJDIR	:= obj
 BINDIR	:= bin
 
@@ -84,8 +96,10 @@ ALLOBJS	:=
 ALLDEPS	:=
 TARGETS	:=
 
+# 将tools/function.mk这个文件在这里展开
 include tools/function.mk
 
+# 指明目录返回一个.c .S文件的列表
 listf_cc = $(call listf,$(1),$(CTYPE))
 
 # for cc
